
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "h'\xec\xd1\xdb-\xe6\x80\xb4\xda\x96\xeb\xf6,\x14\x80"
    
_lr_action_items = {'SCOLON':([2,4,5,6,7,10,],[-8,9,-5,-6,-7,-4,]),'ID':([0,2,5,6,7,],[2,-8,2,-6,-7,]),'INT_TYPE':([0,2,5,6,7,],[6,-8,6,-6,-7,]),'$end':([1,3,8,9,],[-2,-1,0,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'decl':([0,],[1,]),'external_decl':([0,],[3,]),'decl_specs':([0,5,],[4,10,]),'type_spec':([0,5,],[5,5,]),'typedef_name':([0,5,],[7,7,]),'translation_unit':([0,],[8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> translation_unit","S'",1,None,None,None),
  ('translation_unit -> external_decl','translation_unit',1,'p_translation_unit','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',40),
  ('external_decl -> decl','external_decl',1,'p_external_decl','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',48),
  ('decl -> decl_specs SCOLON','decl',2,'p_decl','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',52),
  ('decl_specs -> type_spec decl_specs','decl_specs',2,'p_decl_specs','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',56),
  ('decl_specs -> type_spec','decl_specs',1,'p_decl_specs','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',57),
  ('type_spec -> INT_TYPE','type_spec',1,'p_type_spec','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',61),
  ('type_spec -> typedef_name','type_spec',1,'p_type_spec','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',62),
  ('typedef_name -> ID','typedef_name',1,'p_typedef_name','C:/Users/nidys/PycharmProjects/Merger/parser/Parser.py',66),
]
